spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 179220
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 180000
      auto-commit: true
    thymeleaf:
      cache: false
  # redis配置以及连接池
  data:
    redis:
      host: localhost
      port: 6379
      # 连接超时时间
      timeout: 10000ms
      password: # redis 密码
      client-type: lettuce
      connect-timeout: 5000
      # 这里使用具体的分片
      database: 0
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）默认8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）默认-1
          max-wait: -1ms
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
  cache:
    # 使用redis作为缓存
    type: redis

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cdu.gu.entity
server:
  port: 8088
logging:
  level:
    sql: debug

avatar:
  path: src/main/resources/static/images

hwyun:
  obs:
    accessKey: NJKWNPPTWCRZVM82KDEB
    securityKey: UblF4u1zWJpd8LhuzPVMfYMteq84jwDSLblPIugw
    bucketName: online-chat0
    endPoint: obs.cn-east-3.myhuaweicloud.com
    prifix: /photo
    path: online-chat.obs.cn-east-3.myhuaweicloud.com  #域名，在域名后或目录前加/
txyun:
  obs:
    secretId: AKID62vc7SgvMXdjicIk4SsEUhiUTM2Vjvxl
    secretKey: pV3Qk2VnrkPuKh7ORPI1WwwrW6Wjuypd
    region: ap-chengdu
    bucketName: emos-1317476475
    url: https://emos-1317476475.cos.ap-chengdu.myqcloud.com
    prefix: /photo/